/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.adminobat;

import Controller.KategoriManager;
import Controller.LayananManager;
import Model.KasirDB;
import Model.Kategori;
import Model.Layanan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author root
 */
public class layananForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form layananForm
     */
    KasirDB db;
    LayananManager lm;
    KategoriManager km;

    Layanan layanan;

    DefaultTableModel model;
    ArrayList<Kategori> kategori;
    int selectedRow;
    final TableRowSorter<TableModel> sorter;

    public layananForm(KasirDB kasirdb) throws SQLException {

        this.db = kasirdb;
        lm = new LayananManager(db);
        km = new KategoriManager(db);
//        km.addKategori(new Kategori("Akomodasi", "untuk Akomodasi"));
        model = lm.setToTable();
        kategori = km.getAllData();

        sorter = new TableRowSorter<TableModel>(model);
        initComponents();

        jTable1.setRowSorter(sorter);

        System.out.println(kategori.size());

        for (int i = 0; i < kategori.size(); i++) {

            Item item = new Item(kategori.get(i).getId_kategori(), kategori.get(i).getKategori());
            cb_kategori.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataOperator = new javax.swing.JPanel();
        lbl_nama = new javax.swing.JLabel();
        lbl_id_operator = new javax.swing.JLabel();
        id_tempat_lahir = new javax.swing.JLabel();
        lbl_tanggal_lahir = new javax.swing.JLabel();
        lbl_jenis_kelamin = new javax.swing.JLabel();
        txt_id_layanan = new javax.swing.JTextField();
        txt_layanan = new javax.swing.JTextField();
        txt_desc = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        btn_batal = new javax.swing.JButton();
        notifikasi = new javax.swing.JLabel();
        tabelOperator = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        notifikasi_hapus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Data Layanan");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataOperator.setBackground(new java.awt.Color(255, 255, 255));
        dataOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        dataOperator.setForeground(new java.awt.Color(0, 204, 204));
        dataOperator.setMaximumSize(new java.awt.Dimension(520, 300));
        dataOperator.setMinimumSize(new java.awt.Dimension(520, 300));
        dataOperator.setPreferredSize(new java.awt.Dimension(520, 300));
        dataOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama.setText("Layanan");
        dataOperator.add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lbl_id_operator.setText("ID Layanan");
        dataOperator.add(lbl_id_operator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        id_tempat_lahir.setText("Deskripsi");
        dataOperator.add(id_tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lbl_tanggal_lahir.setText("Harga");
        dataOperator.add(lbl_tanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_jenis_kelamin.setText("Kategori");
        dataOperator.add(lbl_jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        txt_id_layanan.setEditable(false);
        dataOperator.add(txt_id_layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, -1));
        dataOperator.add(txt_layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 330, -1));
        dataOperator.add(txt_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 330, -1));
        dataOperator.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        dataOperator.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, 25));

        jLabel2.setText("Rp.");
        dataOperator.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        cb_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kategoriActionPerformed(evt);
            }
        });
        dataOperator.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, -1));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        dataOperator.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 90, -1));

        notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        dataOperator.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 280, 20));

        getContentPane().add(dataOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 450));

        tabelOperator.setBackground(new java.awt.Color(255, 255, 255));
        tabelOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabelOperator.setForeground(new java.awt.Color(0, 204, 204));
        tabelOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        tabelOperator.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 62, 520, 340));

        jLabel1.setText("Kata Kunci");
        tabelOperator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 90, 25));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        tabelOperator.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 18, 240, 25));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 90, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 90, -1));

        notifikasi_hapus.setForeground(new java.awt.Color(255, 0, 0));
        tabelOperator.add(notifikasi_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 210, 20));

        getContentPane().add(tabelOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 542, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_kategoriActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String layanan = txt_layanan.getText();
        String desc = txt_desc.getText();
        String harga = txt_harga.getText();

        Layanan layanan_input = new Layanan();
        Item item = (Item) cb_kategori.getSelectedItem();

//        System.out.println(cb_kategori.getSelectedItem());
        if (layanan.equals("")) {
            notifikasi.setText("Nama Layanan Belum Diisi");
        } else if (desc.equals("")) {
            notifikasi.setText("Deskripsi Layanana Belum Diisi");
        } else if (harga.equals("")) {
            notifikasi.setText("Harga Layanan Belum Diisi");
        } else {
            layanan_input.setId_kategori(item.getId());
            layanan_input.setLayanan(txt_layanan.getText());
            layanan_input.setBiaya(Double.parseDouble(txt_harga.getText()));
            layanan_input.setKeterangan(txt_desc.getText());

            try {
                if (!txt_id_layanan.getText().equals("")) {
                    layanan_input.setId_layanan(Integer.parseInt(txt_id_layanan.getText()));
                    lm.updateDataLayanan(layanan_input);
                    jTable1.setValueAt(layanan_input.getId_layanan(), selectedRow, 0);
                    jTable1.setValueAt(layanan_input.getLayanan(), selectedRow, 1);
                    jTable1.setValueAt(layanan_input.getId_kategori(), selectedRow, 2);
                    jTable1.setValueAt(layanan_input.getBiaya(), selectedRow, 3);
                    jTable1.setValueAt(layanan_input.getKeterangan(), selectedRow, 4);
                    notifikasi.setText("Data Telah Diubah");
                    clearForm();
                } else {
                    Layanan layanan_baru = lm.addLayanan(layanan_input);
                    model.addRow(new Object[]{layanan_baru.getId_layanan(),
                        layanan_baru.getLayanan(), layanan_baru.getId_kategori(),
                        layanan_baru.getBiaya(), layanan_baru.getKeterangan()});
                    notifikasi.setText("Data Disimpan");
                    clearForm();
                }

            } catch (SQLException ex) {
                Logger.getLogger(layananForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            selectedRow = jTable1.getSelectedRow();
            int column = 0;
            Object object = jTable1.getValueAt(selectedRow, column);
            Layanan layanan_edit = lm.getDataById(Integer.parseInt(object.toString())).get(0);
            cb_kategori.setSelectedItem(km.getDataById(layanan_edit.getId_kategori()).get(0).getKategori());
            txt_id_layanan.setText(layanan_edit.getId_layanan() + "");
            txt_layanan.setText(layanan_edit.getLayanan());
            txt_desc.setText(layanan_edit.getKeterangan());
            txt_harga.setText(layanan_edit.getBiaya() + "");
        } catch (SQLException ex) {
            Logger.getLogger(layananForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            int column = 0;

            Object object = model.getValueAt(row, column);

            Layanan layanan_edit = lm.getDataById(Integer.parseInt(object.toString())).get(0);

            lm.delDataLayanan(layanan_edit);

            model.removeRow(row);
//            sorter.rowsDeleted(row, row);
            notifikasi_hapus.setText("Data Dihapus");
            clearForm();
        } catch (SQLException ex) {
            Logger.getLogger(layananForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        if (txt_cari.getText().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(txt_cari.getText()));
        }
    }//GEN-LAST:event_txt_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<Item> cb_kategori;
    private javax.swing.JPanel dataOperator;
    private javax.swing.JLabel id_tempat_lahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_id_operator;
    private javax.swing.JLabel lbl_jenis_kelamin;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_tanggal_lahir;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JLabel notifikasi_hapus;
    private javax.swing.JPanel tabelOperator;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id_layanan;
    private javax.swing.JTextField txt_layanan;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        txt_id_layanan.setText("");
        txt_layanan.setText("");
        txt_desc.setText("");
        txt_harga.setText("");
    }

}
