/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.kasir;

import Controller.KasirManager;
import Controller.LoginManager;
import Controller.SesiManager;
import Controller.UserManager;
import Model.Kasir;
import Model.KasirDB;
import Model.Login;
import Model.Sessi;
import Model.User;

import app.form.adminkamar.checkinForm;
import app.form.adminkamar.checkoutForm;
import java.awt.Dimension;
import java.beans.PropertyVetoException;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardOpenOption.APPEND;
import static java.nio.file.StandardOpenOption.CREATE;
import java.sql.SQLException;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FormKasir extends java.awt.Frame {

    /**
     * Creates new form FormAdmin
     */
    KasirDB kasirdb; 
    Login login;
    User user;
    
    int kasir_aktif;
    
    KasirManager km;
    ArrayList<Kasir> kasir;
    
    SesiManager sm;
    Sessi sesi;
   
    belanjaForm belanja;
    pembayaranForm bayar;
    checkinForm cekin;
    checkoutForm cekout;
    
    

    public FormKasir(KasirDB kasirdb, Login login) throws SQLException, ParseException {

        initComponents();
        
        setExtendedState(FormKasir.MAXIMIZED_BOTH);
                
        this.kasirdb = kasirdb;
        this.login = login;
        
        sm = new SesiManager(kasirdb);
        km = new KasirManager(kasirdb);
        kasir = km.getAllData();
        
        for(int i=0; i< kasir.size();i++){
            
            Item item = new Item(kasir.get(i).getId_kasir(), kasir.get(i).getKasir());
            cb_kasir.addItem(item);
            
        }
        
        UserManager um = new UserManager(kasirdb);
        user = um.getDataById(login.getId_operator()).get(0);
        
        kasir_aktif=checkKasirAvailable();
        
        if(kasir_aktif <0 ){
            JOptionPane.showMessageDialog(this, jPanel2);
            
            Item selectedItem = (Item) cb_kasir.getSelectedItem();
            boolean br=writeExternalFie(selectedItem.getId());
            kasir_aktif=selectedItem.getId();
        }
        
        sesi=sm.getStatus(kasir_aktif);
        
        
        if(sesi.getStatus().equals("Close")){
            JOptionPane.showMessageDialog(this, "Kasir Belum di Buka oleh admin");
            System.exit(0);
        }
        
//        Prepare InternalFrame
        belanja = new belanjaForm(this.kasirdb, user);
        bayar = new pembayaranForm(this.kasirdb,user,sesi);
        cekin = new checkinForm(this.kasirdb,user);
        cekout = new checkoutForm(this.kasirdb);
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cb_kasir = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        txt_date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_belanja = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_check_out = new javax.swing.JButton();
        btn_check_in = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kasirPane = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_kasir, 0, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setTitle("KASIR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        txt_date.setForeground(new java.awt.Color(255, 0, 0));
        jToolBar1.add(txt_date);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        btn_belanja.setBackground(new java.awt.Color(255, 255, 255));
        btn_belanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashier.png"))); // NOI18N
        btn_belanja.setToolTipText("Tambah Layanan yang digunakan Pasien");
        btn_belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_belanjaActionPerformed(evt);
            }
        });

        btn_bayar.setBackground(new java.awt.Color(255, 255, 255));
        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashier-machine-profile.png"))); // NOI18N
        btn_bayar.setToolTipText("Pembayaran layanan yang digunakan Pasien");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_check_out.setBackground(new java.awt.Color(255, 255, 255));
        btn_check_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check-out.png"))); // NOI18N
        btn_check_out.setToolTipText("Pengunjung Keluar");
        btn_check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_check_outActionPerformed(evt);
            }
        });

        btn_check_in.setBackground(new java.awt.Color(255, 255, 255));
        btn_check_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check-in-desk (1).png"))); // NOI18N
        btn_check_in.setToolTipText("Pengujung Masuk");
        btn_check_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_check_inActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(btn_check_in);
        jLabel1.setText("Masuk");
        jLabel1.setToolTipText("Tambah Data Kunjungan");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Keluar");
        jLabel2.setToolTipText("Tambah Pasien Keluar");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Layanan");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pembayaran");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log Out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_check_in, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_check_out, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_belanja, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_bayar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_check_in, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btn_check_out, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btn_belanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5)))
        );

        kasirPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        kasirPane.setAutoscrolls(true);

        javax.swing.GroupLayout kasirPaneLayout = new javax.swing.GroupLayout(kasirPane);
        kasirPane.setLayout(kasirPaneLayout);
        kasirPaneLayout.setHorizontalGroup(
            kasirPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kasirPaneLayout.setVerticalGroup(
            kasirPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
            .addComponent(kasirPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasirPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_belanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_belanjaActionPerformed
        try {
            
            setInternalFrame(belanja);
           
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_belanjaActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        try {
           
            setInternalFrame(bayar);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_check_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_check_inActionPerformed
        
        try {
            setInternalFrame(cekin);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_check_inActionPerformed

    private void btn_check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_check_outActionPerformed
        try {
            setInternalFrame(cekout);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_check_outActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        try {
            Calendar calender = Calendar.getInstance();

            Date date = new Date();
            
            login.setWaktu_logout(date);
            LoginManager lm= new LoginManager(kasirdb);
            lm.updateLogin(login);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_belanja;
    private javax.swing.JButton btn_check_in;
    private javax.swing.JButton btn_check_out;
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<Item> cb_kasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane kasirPane;
    private javax.swing.JLabel txt_date;
    // End of variables declaration//GEN-END:variables


    private void setInternalFrame(JInternalFrame frame) throws PropertyVetoException{
        
        Dimension desktopSize = kasirPane.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
                (desktopSize.height- jInternalFrameSize.height)/2);
        JInternalFrame[]aktif_frames;
        aktif_frames = kasirPane.getAllFrames();
        
        
        for (JInternalFrame aktif_frame : aktif_frames) {
            if (aktif_frame == frame) {
                frame.setSelected(true);
                return;
            }
        }
        
        frame.setVisible(true);
        kasirPane.add(frame);
        frame.setSelected(true);
        
    }
    
    public void DateHours() {
        Calendar calender = Calendar.getInstance();
        SimpleDateFormat date = new SimpleDateFormat("EEEE, d MMMM yyyy");
        String tanggal = date.format(calender.getTime());
        txt_date.setText(tanggal);
    }

    private int checkKasirAvailable() {
        
        Path file = Paths.get("./logfile.txt");
        int idKasir = -1;
        try (InputStream in = Files.newInputStream(file);
            BufferedReader reader =
              new BufferedReader(new InputStreamReader(in))) {
            String line = null;
            while ((line = reader.readLine()) != null) {
                
                idKasir=Integer.parseInt(line);
                
            }
        } catch (IOException x) {
            System.err.println(x);
            return -1;
        }
        return idKasir;
    } 
    
    private boolean writeExternalFie(int kasirName){
        
        String s = kasirName+"";
        byte data[] = s.getBytes();
        Path p = Paths.get("./logfile.txt");

        try (OutputStream out = new BufferedOutputStream(
          Files.newOutputStream(p, CREATE, APPEND))) {
          out.write(data, 0, data.length);
        } catch (IOException x) {
          System.err.println(x);
          return false;
        }
        
        return true;
    }
}