/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.kasir;

import Controller.CheckInManager;
import Controller.CheckOutManager;
import Controller.PembayaranManager;
import Controller.TransaksiManager;
import Model.InfoCheckIn;
import Model.InfoCheckOut;
import Model.KasirDB;
import Model.Pembayaran;
import Model.Sessi;
import Model.Transaksi;
import Model.User;
import Tools.Report;
import Tools.Widget;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class pembayaranForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form pembayaranForm
     */
    KasirDB db;

    CheckInManager cim;

    CheckOutManager com;

    TransaksiManager tm;

    InfoCheckIn cekin;

    InfoCheckOut cekout;

    ArrayList<Transaksi> transaksi;
    
    ArrayList<Pembayaran> pembayaran;

    DefaultTableModel model;
    
    DefaultTableModel model_histori;

    PembayaranManager pm;

    DecimalFormat myFormatter;
    
    User user;
    
    Sessi sesi;
    
    public pembayaranForm(KasirDB kasirdb, User user, Sessi sesi) throws SQLException, ParseException {

        this.db = kasirdb;
        this.user = user;
        this.sesi = sesi;
        
        cim = new CheckInManager(kasirdb);
        com = new CheckOutManager(kasirdb);
        tm = new TransaksiManager(kasirdb);
        pm = new PembayaranManager(kasirdb);
       
        model = this.setToTable();
        myFormatter = new DecimalFormat("###.###");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_dari = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_banyak_uan = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_untuk_pembayaran = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txt_jumlah_uang = new javax.swing.JTextField();
        ck_rekening = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id_pasien = new javax.swing.JTextField();
        txt_nama_pasien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tgl_masuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tgl_keluar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        notifikasi = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_ttl_byr = new javax.swing.JLabel();
        lbl_sisa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dibayar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        jLabel10.setText("Sudah Terima dari");

        jLabel7.setText("Banyaknya Uang");

        txt_dari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dariActionPerformed(evt);
            }
        });

        txt_banyak_uan.setColumns(20);
        txt_banyak_uan.setRows(5);
        jScrollPane5.setViewportView(txt_banyak_uan);

        jLabel13.setText("Untuk Pembayaran");

        txt_untuk_pembayaran.setColumns(20);
        txt_untuk_pembayaran.setRows(5);
        jScrollPane6.setViewportView(txt_untuk_pembayaran);

        jLabel14.setText("Jumlah Uang");

        txt_jumlah_uang.setEditable(false);

        ck_rekening.setSelected(true);
        ck_rekening.setText("Cetak Rekening");
        ck_rekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_rekeningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dari)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ck_rekening)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_jumlah_uang))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_dari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah_uang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ck_rekening)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Pembayaran");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Pasien");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        jLabel2.setText("Nama Pasien");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));

        txt_id_pasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_pasienKeyPressed(evt);
            }
        });
        jPanel1.add(txt_id_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 190, -1));

        txt_nama_pasien.setEditable(false);
        jPanel1.add(txt_nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 35, 260, -1));

        jLabel3.setText("Tanggal Masuk");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        txt_tgl_masuk.setEditable(false);
        jPanel1.add(txt_tgl_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 63, 260, -1));

        jLabel4.setText("Tanggal Keluar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, -1, -1));

        txt_tgl_keluar.setEditable(false);
        jPanel1.add(txt_tgl_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, -1));

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 20));

        notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 260, 20));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Bayar=Rp.");

        txt_total.setBackground(new java.awt.Color(0, 0, 0));
        txt_total.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 51, 0));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jLabel8.setText("Total Telah di Bayar");

        jLabel9.setText("Sisa");

        lbl_sisa.setForeground(new java.awt.Color(255, 0, 0));

        jLabel11.setText("Di Bayar");

        txt_dibayar.setForeground(new java.awt.Color(0, 153, 51));
        txt_dibayar.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_ttl_byr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_sisa, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(txt_dibayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_ttl_byr))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_dibayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lbl_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(6, 6, 6))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transfer.png"))); // NOI18N
        jButton1.setText("Kwintansi");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 30, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nfc.png"))); // NOI18N
        jButton3.setText("NFC");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 104, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wallet.png"))); // NOI18N
        jButton4.setText("E Wallet");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 30, 104, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         findByID();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_jumlah_uang.setText(txt_dibayar.getText());
        int a= JOptionPane.showConfirmDialog(null, jPanel5, "Kwitansi", JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        System.out.println(a);
        if (a==0) {
            Report.makeKwitansi("kwitansi", cekin.getId_checkIn(),txt_dari.getText(),txt_banyak_uan.getText(),txt_untuk_pembayaran.getText(),txt_jumlah_uang.getText() ,db);
            System.out.println(ck_rekening.isSelected());
            if(ck_rekening.isSelected()) {
                double telah_bayar = Double.parseDouble(txt_jumlah_uang.getText())+Double.parseDouble(lbl_ttl_byr.getText());
                Report.makeRekening("rekening_pasien", cekin.getId_checkIn(),telah_bayar,db);
            }
          
        }
//        Report.makeInvoice("rekening_pasien", cekin.getId_checkIn(), db);s
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            
            Calendar calender = Calendar.getInstance();
            SimpleDateFormat date = new SimpleDateFormat("MMM d, yyyy");
            String tanggal = date.format(calender.getTime());
        
            Pembayaran pembayaran_baru = new Pembayaran();
            
            pembayaran_baru.setId_Checkin(cekin.getId_checkIn());
            pembayaran_baru.setJumlah(Double.parseDouble(txt_total.getText()));
           
        
            pembayaran_baru.setTanggal(Widget.convertJavaDateToSqlDate(calender.getTime()));
            
            pembayaran_baru.setId_user(user.getId_user());
            pembayaran_baru.setId_sesi(sesi.getId_sesi());
            
            double hitung = Double.parseDouble(lbl_sisa.getText())-Double.parseDouble(txt_total.getText());
            
            if (hitung == 0) pembayaran_baru.setStatus(1);
            else pembayaran_baru.setStatus(0);
            
            try {
                lbl_ttl_byr.setText(myFormatter.format(pm.getPembayaran(cekin.getId_checkIn())));
            } catch (ParseException ex) {
                Logger.getLogger(pembayaranForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            txt_dibayar.setText(pm.addPembayaran(pembayaran_baru).getJumlah()+"");
            
            txt_total.setText("");
            double sisa = Double.parseDouble(lbl_total.getText())-Double.parseDouble(lbl_ttl_byr.getText())-Double.parseDouble(txt_dibayar.getText());
            lbl_sisa.setText(myFormatter.format(sisa));
            
        } catch (SQLException ex) {
            Logger.getLogger(pembayaranForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key=evt.getKeyCode();
        
        System.out.println(key+"");
    }//GEN-LAST:event_formKeyPressed

    private void txt_id_pasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_pasienKeyPressed
       if (evt.getKeyCode() == 112) {
          findByID();
           try {
               model_histori = pm.setToTable(pembayaran);
               jTable2.setModel(model_histori);
               JOptionPane.showConfirmDialog(null, jPanel4, "Histori Pembayaran", JOptionPane.CLOSED_OPTION, JOptionPane.PLAIN_MESSAGE);
           } catch (SQLException | ParseException ex) {
               Logger.getLogger(pembayaranForm.class.getName()).log(Level.SEVERE, null, ex);
           }
    
       }
    }//GEN-LAST:event_txt_id_pasienKeyPressed

    private void txt_dariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dariActionPerformed

    private void ck_rekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_rekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck_rekeningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ck_rekening;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_sisa;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_ttl_byr;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JTextArea txt_banyak_uan;
    private javax.swing.JTextField txt_dari;
    private javax.swing.JLabel txt_dibayar;
    private javax.swing.JTextField txt_id_pasien;
    private javax.swing.JTextField txt_jumlah_uang;
    private javax.swing.JTextField txt_nama_pasien;
    private javax.swing.JTextField txt_tgl_keluar;
    private javax.swing.JTextField txt_tgl_masuk;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextArea txt_untuk_pembayaran;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel setToTable() throws SQLException {

        Object[][] rowData = new Object[0][4];

        Object columnNames[] = {"NAMA LAYANAN", "HARGA", "JUMLAH", "TOTAL", "TANGGAL"};

        DefaultTableModel jtable = new DefaultTableModel(rowData, columnNames);

        return jtable;
    }

    private void setTableData(ArrayList<Transaksi> transaksis) {

        double total = 0;

        for (int i = 0; i < transaksis.size(); i++) {

            model.addRow(new Object[]{
                transaksis.get(i).getNamaLayanan(),
                transaksis.get(i).getHarga(),
                transaksis.get(i).getJumlah(),
                transaksis.get(i).getHarga() * transaksis.get(i).getJumlah(),
                transaksis.get(i).getTgl_layanan()
                    
            });

           
            total = total + (transaksis.get(i).getHarga() * transaksis.get(i).getJumlah());    
            
        }
        lbl_total.setText(myFormatter.format(total));
    }
    
 
    private void findByID(){
        try {
            ArrayList <InfoCheckIn> cekins = cim.getDataByIdPasien(Integer.parseInt(txt_id_pasien.getText()));

            if(cekins.size() >=1){
                ArrayList<InfoCheckIn> checkin_belum_bayar;
                checkin_belum_bayar = new ArrayList<>();
                for (int i=0; i<cekins.size();i++){
                pembayaran = pm.getDataByIdCheckIn(cekins.get(i).getId_checkIn());
                    if(pembayaran.get(0).getStatus()==0){
                        checkin_belum_bayar.add(cekins.get(i));
                    }
                }
                if(checkin_belum_bayar.size()==1){
                    cekin=checkin_belum_bayar.get(0);
                    ArrayList<InfoCheckOut>cekouts = com.getDataByIdCheckIn(cekin.getId_checkIn());
                    if(cekouts == null)JOptionPane.showMessageDialog(null, "Belum check out");
                    else if(cekouts.size() == 1){
                            cekout = cekouts.get(0);
                            txt_tgl_keluar.setText(cekout.getTgl_keluar().toString());
                        }
                        
                        
                        txt_nama_pasien.setText(cekin.getNama());
                        txt_tgl_masuk.setText(cekin.getTgl_masuk().toString());

                        transaksi = tm.getDataByKodeKunjungan(cekin.getId_checkIn());
                        if(model.getRowCount()==0) this.setTableData(transaksi);
                        lbl_ttl_byr.setText(myFormatter.format(pm.getPembayaran(cekin.getId_checkIn())));
                        double sisa = Double.parseDouble(lbl_total.getText())-Double.parseDouble(lbl_ttl_byr.getText())-Double.parseDouble(txt_dibayar.getText());
                        lbl_sisa.setText(myFormatter.format(sisa));
                    }
                    else if(checkin_belum_bayar.size()<=0){
                        JOptionPane.showMessageDialog(null, "Tidak ada bon pembayaran");
                    }
                    else if(checkin_belum_bayar.size()>=2){
                        JOptionPane.showMessageDialog(null, "Ada lebih dari 1 kunjungan belum lunas");
                    }
               
            }else{
                JOptionPane.showMessageDialog(null, "Tidak ada Data Kunjungan");
            }                
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(belanjaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
