/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.superuser;

import Controller.KasirManager;
import Controller.PembayaranManager;
import Controller.SesiManager;
import Model.Kasir;
import Model.KasirDB;
import Model.Sessi;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andreo
 */
public class formSessi extends javax.swing.JInternalFrame {

    KasirDB kasirdb;
    SesiManager sm;
    KasirManager km; 
    PembayaranManager pm;
    ArrayList<Kasir> kasir;
    
    SimpleDateFormat formatter;
    
    DefaultTableModel modelSesi;
    DefaultTableModel modelKasir;
    
    Sessi sesiTerakhir;
    
    
    public formSessi(KasirDB db) throws SQLException, ParseException {
        
        this.kasirdb = db;
        km = new KasirManager(kasirdb);
        sm = new SesiManager(kasirdb);
        pm = new PembayaranManager(kasirdb);
        
        modelSesi = this.setToTable();
        modelKasir = km.setToTable();
        
        kasir = km.getAllData();
        
        formatter= new SimpleDateFormat("yyyy-MM-dd");
        
        sesiTerakhir=null;
        
        initComponents();
        
        for (int i = 0; i < kasir.size();i++){
            
            Item item = new Item(kasir.get(i).getId_kasir(), kasir.get(i).getKasir());
            cb_kasir.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_kasir = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_kasir = new javax.swing.JComboBox<>();
        txt_saldo_awal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_buka_kasir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_saldo_akhir = new javax.swing.JTextField();
        btn_tutup_kasir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Kasir");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jTable2.setModel(modelKasir);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_simpan))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kasir"));

        jLabel2.setText("Kasir");

        cb_kasir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_kasirItemStateChanged(evt);
            }
        });

        jLabel3.setText("Saldo Awal");

        btn_buka_kasir.setText("Buka Kasir");
        btn_buka_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buka_kasirActionPerformed(evt);
            }
        });

        jButton2.setText("Cek Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        txt_status.setEditable(false);

        jLabel4.setText("Saldo Akhir");

        txt_saldo_akhir.setEditable(false);

        btn_tutup_kasir.setText("Tutup kasir");
        btn_tutup_kasir.setEnabled(false);
        btn_tutup_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutup_kasirActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_saldo_akhir)
                            .addComponent(txt_saldo_awal)
                            .addComponent(txt_status)
                            .addComponent(cb_kasir, 0, 202, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buka_kasir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tutup_kasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_saldo_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buka_kasir))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_saldo_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tutup_kasir))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat"));

        jTable1.setModel(modelSesi);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       JOptionPane.showConfirmDialog(null, jPanel3, "Kasir", JOptionPane.CLOSED_OPTION, JOptionPane.PLAIN_MESSAGE);                
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            Kasir kasir_input = new Kasir(txt_kasir.getText());
            Kasir input=km.addKasir(kasir_input);
            
            modelKasir.addRow(new Object[]{input.getId_kasir(), input.getKasir()});
            Item item = new Item(input.getId_kasir(),input.getKasir());
            cb_kasir.addItem(item);
            
            Sessi sesi = new Sessi();
            sesi.setStatus(0);
            
            sm.addSessi(sesi);
            
        } catch (SQLException ex) {
            Logger.getLogger(formSessi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        checkStatus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_buka_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buka_kasirActionPerformed
        
        try {
            Sessi newsesi = new Sessi();
            Item item = (Item) cb_kasir.getSelectedItem();
            newsesi.setId_kasir(item.getId());
            newsesi.setSaldo_awal(Double.parseDouble(txt_saldo_awal.getText()));
            
            Sessi sesi_input=sm.addSessi(newsesi);
            
            if(sesi_input.getId_sesi()>=0){
                btn_tutup_kasir.setEnabled(true);
                btn_buka_kasir.setEnabled(false);
                txt_saldo_awal.setEnabled(false);
                txt_saldo_akhir.setEnabled(false);
                txt_status.setText("open");
              System.out.print(sesi_input.getId_sesi());
            }
            
             checkStatus();
        } catch (SQLException ex) {
            Logger.getLogger(formSessi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buka_kasirActionPerformed

    private void cb_kasirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_kasirItemStateChanged
       clearForm();
    }//GEN-LAST:event_cb_kasirItemStateChanged

    private void btn_tutup_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tutup_kasirActionPerformed
        try {
            sesiTerakhir.setSaldo_akhir(Double.parseDouble(txt_saldo_akhir.getText()));
            sesiTerakhir.setStatus(0);
            sm.updateDataSesi(sesiTerakhir);
             checkStatus();
            
        } catch (SQLException ex) {
            Logger.getLogger(formSessi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_tutup_kasirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buka_kasir;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tutup_kasir;
    private javax.swing.JComboBox<Item> cb_kasir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_kasir;
    private javax.swing.JTextField txt_saldo_akhir;
    private javax.swing.JTextField txt_saldo_awal;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables


 private DefaultTableModel setToTable(){
        Object[][] rowData = new Object[0][7];
        
        
         Object column[] = {"ID ", "ID KASIR", "STATUS", "BUKA", "SALDO", "TUTUP", "SALDO"};

        DefaultTableModel jtable = new DefaultTableModel(rowData, column);

        return jtable;
  
    }    
private void setTableData(ArrayList<Sessi> sessis) throws SQLException, ParseException {
        
        modelSesi.setRowCount(0);
        for (int i = 0; i < sessis.size(); i++) {
            
           
            modelSesi.addRow(new Object[]{
                sessis.get(i).getId_sesi(),
                km.getDataById(sessis.get(i).getId_kasir()).get(0).getKasir(),
                sessis.get(i).getStatus(),
                sessis.get(i).getTime_open_sesi(),
                sessis.get(i).getSaldo_awal(),
                sessis.get(i).getTime_close_sesi(),
                sessis.get(i).getSaldo_akhir()
                
            });

        }

    }

    void clearForm(){
        txt_status.setText("");
        txt_saldo_akhir.setText("");
        txt_saldo_awal.setText("");
        btn_buka_kasir.setEnabled(false);
        btn_tutup_kasir.setEnabled(false);
    }
    
    void checkStatus(){
        try {
            Item item = (Item) cb_kasir.getSelectedItem();
            ArrayList<Sessi> sesi_selected=sm.getDataByIdKasir(item.getId());
             
            this.setTableData(sesi_selected);
            
            
            if(sm.getStatus(item.getId())!= null){
                sesiTerakhir= sm.getStatus(item.getId());
                txt_status.setText(sesiTerakhir.getStatus());
                
                this.setTableData(sesi_selected);
                if(txt_status.getText().equals("Open")) {
                    btn_buka_kasir.setEnabled(false);
                    btn_tutup_kasir.setEnabled(true);
                    txt_saldo_awal.setEnabled(false);
                    txt_saldo_awal.setText(sesiTerakhir.getSaldo_awal()+"");
                    
                    double saldo=pm.getJumlahBySesi(sesiTerakhir.getId_sesi());
                    double total = sesiTerakhir.getSaldo_awal()+saldo;
                    txt_saldo_akhir.setText(total+"");
                    
                }else{
                    btn_buka_kasir.setEnabled(true);
                    btn_tutup_kasir.setEnabled(false);
                    txt_saldo_awal.setEnabled(true);
                    txt_saldo_awal.setText("");
                    txt_saldo_akhir.setText("");
                }
            }
            else{
                txt_status.setText("Close");
                btn_buka_kasir.setEnabled(true);
                btn_tutup_kasir.setEnabled(false);
                txt_saldo_awal.setEnabled(true);
                txt_saldo_awal.setText("");
            }
            
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(formSessi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
