/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.superuser;

import Controller.UserManager;
import Model.KasirDB;
import Model.Ruangan;
import Model.User;
import Tools.Widget;
import app.form.adminkamar.ruanganForm;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author root
 */
public class penggunaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    UserManager userman;
    KasirDB koneksiDB;
    DefaultTableModel model;
    int selectedRow;
    final TableRowSorter<TableModel> sorter;

    public penggunaForm(KasirDB kasirdb) throws SQLException, ParseException {

        this.koneksiDB = kasirdb;
        userman = new UserManager(koneksiDB);
        model = userman.setToTable();

        sorter = new TableRowSorter<TableModel>(model);
        initComponents();

        jTable1.setRowSorter(sorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataOperator = new javax.swing.JPanel();
        lbl_nama = new javax.swing.JLabel();
        lbl_id_operator = new javax.swing.JLabel();
        id_tempat_lahir = new javax.swing.JLabel();
        lbl_tanggal_lahir = new javax.swing.JLabel();
        lbl_jenis_kelamin = new javax.swing.JLabel();
        txt_id_operator = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tempat = new javax.swing.JTextField();
        cb_kelamin = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        lbl_tanggal_lahir1 = new javax.swing.JLabel();
        txt_telp = new javax.swing.JTextField();
        dc_tanggal = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nama1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        id_tempat_lahir1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_jenis_kelamin1 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        notifikasi = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        tabelOperator = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        notifikasi_hapus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Data Pengguna");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 500));
        setMinimumSize(new java.awt.Dimension(1100, 500));
        setPreferredSize(new java.awt.Dimension(1175, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataOperator.setBackground(new java.awt.Color(255, 255, 255));
        dataOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        dataOperator.setForeground(new java.awt.Color(0, 204, 204));
        dataOperator.setMaximumSize(new java.awt.Dimension(520, 300));
        dataOperator.setMinimumSize(new java.awt.Dimension(520, 300));
        dataOperator.setPreferredSize(new java.awt.Dimension(520, 300));
        dataOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama.setText("Nama");
        dataOperator.add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_id_operator.setText("ID Pengguna");
        dataOperator.add(lbl_id_operator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        id_tempat_lahir.setText("Tempat Lahir");
        dataOperator.add(id_tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_tanggal_lahir.setText("Tanggal Lahir");
        dataOperator.add(lbl_tanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_jenis_kelamin.setText("Jenis Kelamin");
        dataOperator.add(lbl_jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txt_id_operator.setEditable(false);
        dataOperator.add(txt_id_operator, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));
        dataOperator.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 320, -1));
        dataOperator.add(txt_tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 270, -1));

        cb_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        dataOperator.add(cb_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        dataOperator.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 385, 90, 25));

        jLabel2.setText("Alamat");
        dataOperator.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane2.setViewportView(txt_alamat);

        dataOperator.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 165, 320, -1));

        lbl_tanggal_lahir1.setText("Telp/HP");
        dataOperator.add(lbl_tanggal_lahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        dataOperator.add(txt_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 150, -1));
        dataOperator.add(dc_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, -1));
        dataOperator.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, 440, 10));

        lbl_nama1.setText("Username");
        dataOperator.add(lbl_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        dataOperator.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 230, -1));

        id_tempat_lahir1.setText("Password");
        dataOperator.add(id_tempat_lahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        dataOperator.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, -1));

        lbl_jenis_kelamin1.setText("Status");
        dataOperator.add(lbl_jenis_kelamin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Kasir" }));
        dataOperator.add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 140, -1));

        notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        dataOperator.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 280, 20));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        dataOperator.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 385, 90, -1));

        getContentPane().add(dataOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 460, 460));

        tabelOperator.setBackground(new java.awt.Color(255, 255, 255));
        tabelOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabelOperator.setForeground(new java.awt.Color(0, 204, 204));
        tabelOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(model);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        tabelOperator.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 62, 680, 340));

        jLabel1.setText("Kata Kunci");
        tabelOperator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 90, 25));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        tabelOperator.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 18, 240, 25));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 90, -1));

        notifikasi_hapus.setForeground(new java.awt.Color(255, 0, 0));
        tabelOperator.add(notifikasi_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 210, 20));

        getContentPane().add(tabelOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama_pengguna = txt_nama.getText();
        String tempat_lahir = txt_tempat.getText();
//        Date tgl_lahir = (Date) dc_tanggal.getDate();
        String jenkel = (String) cb_kelamin.getSelectedItem();
        String alamat = txt_alamat.getText();
        String telp = txt_telp.getText();
        String username = txt_username.getText();
        String password = txt_password.getText();

        User user = new User();
        user.setName(txt_nama.getText());
        user.setTempat(txt_tempat.getText());
        user.setTgl_lahir(Widget.convertJavaDateToSqlDate(dc_tanggal.getDate()));
        user.setKelamin(cb_kelamin.getSelectedIndex());
        user.setAlamat(txt_alamat.getText());
        user.setTelp(txt_telp.getText());

        user.setUsername(txt_username.getText());
        user.setPassword(txt_password.getText());
        user.setStatus(User.type.valueOf(cb_status.getItemAt(cb_status.getSelectedIndex())));

        if (nama_pengguna.equals("")) {
            notifikasi.setText("Nama Belum Diisi");
        } else if (tempat_lahir.equals("")) {
            notifikasi.setText("Tampat Lahir Belum Diisi");
        } else if (jenkel.equals("")) {
            notifikasi.setText("Jenis Kelamin Belum Dipilih");
        } else if (alamat.equals("")) {
            notifikasi.setText("Alamat Belum Diisi");
        } else if (telp.equals("")) {
            notifikasi.setText("Telepon Belum Diisi");
        } else if (username.equals("")) {
            notifikasi.setText("Username Belum Diisi");
        } else if (password.equals("")) {
            notifikasi.setText("Password Belum Diisi");
        } else {
            try {
                if (!txt_id_operator.getText().equals("")) {
                    user.setId_user(Integer.parseInt(txt_id_operator.getText()));
                    userman.updateDataUser(user);
                    jTable1.setValueAt(user.getId_user(), selectedRow, 0);
                    jTable1.setValueAt(user.getName(), selectedRow, 1);
                    jTable1.setValueAt(user.getTempat(), selectedRow, 2);
                    jTable1.setValueAt(user.getTgl_lahir(), selectedRow, 3);
                    jTable1.setValueAt(cb_kelamin.getSelectedItem(), selectedRow, 4);

//                    jTable1.setValueAt(user.getKelamin(), selectedRow, 4);
                    jTable1.setValueAt(user.getAlamat(), selectedRow, 5);
                    jTable1.setValueAt(user.getTelp(), selectedRow, 6);
                    jTable1.setValueAt(user.getUsername(), selectedRow, 7);
                    jTable1.setValueAt(user.getStatus(), selectedRow, 8);
                    jTable1.setValueAt(user.getPassword(), selectedRow, 9);
                    notifikasi.setText("Data Telah Diubah");
                    clearform();
                } else {
                    User user_baru = userman.addUser(user);

                    model.addRow(new Object[]{user_baru.getId_user(), user_baru.getName(), user_baru.getTempat(), user_baru.getTgl_lahir(), Widget.convertGender(user_baru.getKelamin()), user_baru.getAlamat(), user_baru.getTelp(), user_baru.getUsername(), user_baru.getStatus(),
                        user_baru.getPassword()});
                    notifikasi.setText("Data Disimpan");
                    clearform();
                }
            } catch (SQLException ex) {
                Logger.getLogger(penggunaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            selectedRow = jTable1.getSelectedRow();
            int column = 0;
            Object object = jTable1.getValueAt(selectedRow, column);
            User user_edit = userman.getDataById(Integer.parseInt(object.toString())).get(0);

            txt_id_operator.setText("" + user_edit.getId_user());
            txt_nama.setText(user_edit.getName());
            txt_tempat.setText(user_edit.getTempat());
            dc_tanggal.setDate(user_edit.getTgl_lahir());
            cb_kelamin.setSelectedIndex(user_edit.getKelamin());
            txt_alamat.setText(user_edit.getAlamat());
            txt_telp.setText(user_edit.getTelp());
            txt_username.setText(user_edit.getUsername());
            txt_password.setText(user_edit.getPassword());
            cb_status.setSelectedItem(user_edit.getStatus());

        } catch (SQLException ex) {
            Logger.getLogger(penggunaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(penggunaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            int column = 0;

            Object object = jTable1.getValueAt(row, column);

            User user_edit = userman.getDataById(Integer.parseInt(object.toString())).get(0);
            userman.delDataUser(user_edit);
            model.removeRow(row);
            notifikasi_hapus.setText("Data Dihapus");
            clearform();
        } catch (SQLException ex) {
            Logger.getLogger(penggunaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(penggunaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        clearform();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        if (txt_cari.getText().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(txt_cari.getText()));
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    public void clearform() {
        txt_id_operator.setText("");
        txt_nama.setText("");
        txt_tempat.setText("");
//        cb_kelamin.setSelectedItem("");
        txt_alamat.setText("");
        txt_telp.setText("");
        txt_password.setText("");
        txt_username.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_kelamin;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JPanel dataOperator;
    private com.toedter.calendar.JDateChooser dc_tanggal;
    private javax.swing.JLabel id_tempat_lahir;
    private javax.swing.JLabel id_tempat_lahir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_id_operator;
    private javax.swing.JLabel lbl_jenis_kelamin;
    private javax.swing.JLabel lbl_jenis_kelamin1;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nama1;
    private javax.swing.JLabel lbl_tanggal_lahir;
    private javax.swing.JLabel lbl_tanggal_lahir1;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JLabel notifikasi_hapus;
    private javax.swing.JPanel tabelOperator;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_operator;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_telp;
    private javax.swing.JTextField txt_tempat;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private void newFilter() {
        TableRowSorter sorter = new TableRowSorter<>(model);
        RowFilter< User, Object> rf = null;
        //If current expression doesn't parse, don't update.
        try {
            rf = RowFilter.regexFilter(txt_cari.getText(), 0);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rf);
    }
}
