/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.adminkamar;

import Controller.PasienManager;
import Model.KasirDB;
import Model.Pasien;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Tools.*;
import java.text.ParseException;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author root
 */
public class pasienForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    PasienManager pasienman;
    DefaultTableModel model;
    KasirDB koneksiDB;
    int selectedRow;
    final TableRowSorter<TableModel> sorter;

    public pasienForm(KasirDB kasirdb) throws SQLException, ParseException {

        this.koneksiDB = kasirdb;
        pasienman = new PasienManager(koneksiDB);
        model = pasienman.setToTable();

        sorter = new TableRowSorter<TableModel>(model);
        initComponents();

        jTable1.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataOperator = new javax.swing.JPanel();
        lbl_nama = new javax.swing.JLabel();
        lbl_id_operator = new javax.swing.JLabel();
        id_tempat_lahir = new javax.swing.JLabel();
        lbl_tanggal_lahir = new javax.swing.JLabel();
        lbl_jenis_kelamin = new javax.swing.JLabel();
        txt_id_pasien = new javax.swing.JTextField();
        txt_nama_pasien = new javax.swing.JTextField();
        txt_tempat = new javax.swing.JTextField();
        cb_kelamin = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        notifikasi = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        dc_tanggal = new com.toedter.calendar.JDateChooser();
        tabelOperator = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        notifikasi_hapus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Data Pasien");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1078, 475));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataOperator.setBackground(new java.awt.Color(255, 255, 255));
        dataOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        dataOperator.setForeground(new java.awt.Color(0, 204, 204));
        dataOperator.setMaximumSize(new java.awt.Dimension(520, 300));
        dataOperator.setMinimumSize(new java.awt.Dimension(520, 300));
        dataOperator.setPreferredSize(new java.awt.Dimension(520, 300));
        dataOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama.setText("Nama");
        dataOperator.add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_id_operator.setText("ID Pasien");
        dataOperator.add(lbl_id_operator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        id_tempat_lahir.setText("Tempat Lahir");
        dataOperator.add(id_tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_tanggal_lahir.setText("Tanggal Lahir");
        dataOperator.add(lbl_tanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_jenis_kelamin.setText("Jenis Kelamin");
        dataOperator.add(lbl_jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txt_id_pasien.setEditable(false);
        dataOperator.add(txt_id_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, -1));
        dataOperator.add(txt_nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 390, -1));
        dataOperator.add(txt_tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 320, -1));

        cb_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        dataOperator.add(cb_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        dataOperator.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, 30));

        jLabel2.setText("Alamat");
        dataOperator.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane2.setViewportView(txt_alamat);

        dataOperator.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 165, 390, -1));

        notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        dataOperator.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 280, 20));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        dataOperator.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 90, 30));
        dataOperator.add(dc_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, -1));

        getContentPane().add(dataOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, 444));

        tabelOperator.setBackground(new java.awt.Color(255, 255, 255));
        tabelOperator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabelOperator.setForeground(new java.awt.Color(0, 204, 204));
        tabelOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        tabelOperator.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 62, 520, 330));

        jLabel1.setText("Kata Kunci");
        tabelOperator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 90, 25));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        tabelOperator.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 18, 220, 25));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        tabelOperator.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, -1));

        notifikasi_hapus.setForeground(new java.awt.Color(255, 0, 0));
        tabelOperator.add(notifikasi_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 210, 20));

        jButton1.setText("Cetak Kartu Pasien");
        tabelOperator.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        getContentPane().add(tabelOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 0, 548, 444));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama_pasien = txt_nama_pasien.getText();
        String tempat_lahir = txt_tempat.getText();
//        Date tgl_lahir = (Date) dc_tanggal.getDate();
        String jenkel = (String) cb_kelamin.getSelectedItem();
        String alamat = txt_alamat.getText();

        Pasien pasien = new Pasien();
        pasien.setName(txt_nama_pasien.getText());
        pasien.setTmpt_lahir(txt_tempat.getText());
        pasien.setTgl_lahir(Widget.convertJavaDateToSqlDate(dc_tanggal.getDate()));
        pasien.setJenkel(cb_kelamin.getItemAt(cb_kelamin.getSelectedIndex()));
        pasien.setAlamat(txt_alamat.getText());

        if (nama_pasien.equals("")) {
            notifikasi.setText("Nama Belum Diisi");
        } else if (tempat_lahir.equals("")) {
            notifikasi.setText("Tampat Lahir Belum Diisi");
        } else if (jenkel.equals("")) {
            notifikasi.setText("Jenis Kelamin Belum Dipilih");
        } else if (alamat.equals("")) {
            notifikasi.setText("Alamat Belum Diisi");
        } else {
            try {
                if (!txt_id_pasien.getText().equals("")) {
                    pasien.setId_pasien(Integer.parseInt(txt_id_pasien.getText()));
                    pasienman.upDataPasien(pasien);
                    jTable1.setValueAt(pasien.getId_pasien(), selectedRow, 0);
                    jTable1.setValueAt(pasien.getName(), selectedRow, 1);
                    jTable1.setValueAt(pasien.getTmpt_lahir(), selectedRow, 2);
                    jTable1.setValueAt(pasien.getTgl_lahir(), selectedRow, 3);
                    jTable1.setValueAt(pasien.getJenkel(), selectedRow, 4);
                    jTable1.setValueAt(pasien.getAlamat(), selectedRow, 5);
                    notifikasi.setText("Data Telah Diubah");
                    clearform();
                } else {
                    Pasien pasien_baru = pasienman.addDataPasien(pasien);
                    model.addRow(new Object[]{pasien_baru.getId_pasien(), pasien_baru.getName(),
                        pasien_baru.getTmpt_lahir(), pasien_baru.getTgl_lahir(), pasien_baru.getJenkel(), pasien_baru.getAlamat()});
                    notifikasi.setText("Data Disimpan");
                    clearform();
                }
            } catch (SQLException ex) {
                Logger.getLogger(pasienForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            selectedRow = jTable1.getSelectedRow();
            int column = 0;
            Object object = jTable1.getValueAt(selectedRow, column);
            Pasien pasien_edit = pasienman.getDataById(Integer.parseInt(object.toString())).get(0);

            txt_id_pasien.setText("" + pasien_edit.getId_pasien());
            txt_nama_pasien.setText(pasien_edit.getName());
            txt_tempat.setText(pasien_edit.getTmpt_lahir());
            dc_tanggal.setDate(pasien_edit.getTgl_lahir());
            cb_kelamin.setSelectedItem(pasien_edit.getJenkel());
            txt_alamat.setText(pasien_edit.getAlamat());

        } catch (SQLException ex) {
            Logger.getLogger(pasienForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pasienForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            int column = 0;

            Object object = model.getValueAt(row, column);
            Pasien pasien_hapus = pasienman.getDataById(Integer.parseInt(object.toString())).get(0);
            pasienman.delDataPasien(pasien_hapus);
            jTable1.remove(row);
//            sorter.rowsDeleted(row, row);
//            jTable1.setModel(model);
            clearform();
            notifikasi_hapus.setText("Data Dihapus");
        } catch (SQLException ex) {
            Logger.getLogger(pasienForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pasienForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        clearform();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        if (txt_cari.getText().length() == 0) {
            
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(txt_cari.getText()));
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    public void clearform() {
        txt_id_pasien.setText("");
        txt_nama_pasien.setText("");
        txt_tempat.setText("");
//        dc_tanggal.setDateFormatString("");
        cb_kelamin.setSelectedItem("");
        txt_alamat.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_kelamin;
    private javax.swing.JPanel dataOperator;
    private com.toedter.calendar.JDateChooser dc_tanggal;
    private javax.swing.JLabel id_tempat_lahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_id_operator;
    private javax.swing.JLabel lbl_jenis_kelamin;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_tanggal_lahir;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JLabel notifikasi_hapus;
    private javax.swing.JPanel tabelOperator;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_pasien;
    private javax.swing.JTextField txt_nama_pasien;
    private javax.swing.JTextField txt_tempat;
    // End of variables declaration//GEN-END:variables
}
