/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.form.adminkamar;

import Controller.RuanganManager;
import Model.KasirDB;
import Model.Ruangan;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author root
 */
public class ruanganForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form kategoriForm
     */
    RuanganManager ruangman;
    DefaultTableModel model;
    KasirDB koneksiDB;
    int selectedRow;
    final TableRowSorter<TableModel> sorter;

    public ruanganForm(KasirDB kasirdb) throws SQLException, ParseException {

        this.koneksiDB = kasirdb;
        ruangman = new RuanganManager(kasirdb);
        model = ruangman.setToTable();

        sorter = new TableRowSorter<TableModel>(model);
        initComponents();

        jTable.setRowSorter(sorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataOperator2 = new javax.swing.JPanel();
        lbl_nama2 = new javax.swing.JLabel();
        lbl_id_operator2 = new javax.swing.JLabel();
        txt_id_ruang = new javax.swing.JTextField();
        txt_nama_ruang = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        notifikasi = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        tabelOperator2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        notifikasi_hapus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Data Ruang");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataOperator2.setBackground(new java.awt.Color(255, 255, 255));
        dataOperator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataOperator2.setForeground(new java.awt.Color(0, 204, 204));
        dataOperator2.setMaximumSize(new java.awt.Dimension(520, 300));
        dataOperator2.setMinimumSize(new java.awt.Dimension(520, 300));
        dataOperator2.setPreferredSize(new java.awt.Dimension(520, 300));
        dataOperator2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama2.setText("Nama Ruang");
        dataOperator2.add(lbl_nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_id_operator2.setText("ID Ruangan");
        dataOperator2.add(lbl_id_operator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_id_ruang.setEditable(false);
        dataOperator2.add(txt_id_ruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, -1));
        dataOperator2.add(txt_nama_ruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 280, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        dataOperator2.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 25));

        notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        dataOperator2.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 280, 20));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        dataOperator2.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 90, -1));

        getContentPane().add(dataOperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        tabelOperator2.setBackground(new java.awt.Color(255, 255, 255));
        tabelOperator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelOperator2.setForeground(new java.awt.Color(0, 204, 204));
        tabelOperator2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kata Kunci");
        tabelOperator2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 90, 25));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        tabelOperator2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 18, 210, 25));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        tabelOperator2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tabelOperator2.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, -1));

        notifikasi_hapus.setForeground(new java.awt.Color(255, 0, 0));
        tabelOperator2.add(notifikasi_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, 20));

        jTable.setModel(model);
        jScrollPane1.setViewportView(jTable);

        tabelOperator2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 200));

        getContentPane().add(tabelOperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama_kamar = txt_nama_ruang.getText();

        Ruangan ruangan = new Ruangan();
        ruangan.setNama_ruang(txt_nama_ruang.getText());

        if (nama_kamar.equals("")) {
            notifikasi.setText("Nama Ruang Belum Diisi");
        } else {
            try {
                if (!txt_id_ruang.getText().equals("")) {
                    ruangan.setId_ruangan(Integer.parseInt(txt_id_ruang.getText()));
                    ruangman.updateDataRuangan(ruangan);
                    jTable.setValueAt(ruangan.getId_ruangan(), selectedRow, 0);
                    jTable.setValueAt(ruangan.getNama_ruang(), selectedRow, 1);
                    notifikasi.setText("Data Telah Diubah");
                    clearform();
                } else {
//                    ruangman.addRuangan(ruangan);
                    Ruangan ruangan_baru = ruangman.addRuangan(ruangan);
                    model.addRow(new Object[]{ruangan_baru.getId_ruangan(), ruangan_baru.getNama_ruang()});
                    notifikasi.setText("Data Disimpan");
                    clearform();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ruanganForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            int row = jTable.getSelectedRow();
            int column = 0;

            Object object = jTable.getValueAt(row, column);

            Ruangan ruangan_edit = ruangman.getDataById(Integer.parseInt(object.toString())).get(0);

            txt_id_ruang.setText("" + ruangan_edit.getId_ruangan());
            txt_nama_ruang.setText(ruangan_edit.getNama_ruang());

        } catch (SQLException ex) {
            Logger.getLogger(ruanganForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int row = jTable.getSelectedRow();
            int column = 0;

            Object object = jTable.getValueAt(row, column);

            Ruangan ruangan_edit = ruangman.getDataById(Integer.parseInt(object.toString())).get(0);
            txt_id_ruang.setText("" + ruangan_edit.getId_ruangan());
            txt_nama_ruang.setText(ruangan_edit.getNama_ruang());
            ruangman.delDataRuangan(ruangan_edit);
            model.removeRow(row);
//            sorter.rowsDeleted(row, row);
            clearform();
            notifikasi_hapus.setText("Data Dihapus");

        } catch (SQLException ex) {
            Logger.getLogger(ruanganForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        clearform();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        if (txt_cari.getText().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(txt_cari.getText()));
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    public void clearform() {
        txt_id_ruang.setText("");
        txt_nama_ruang.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JPanel dataOperator2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lbl_id_operator2;
    private javax.swing.JLabel lbl_nama2;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JLabel notifikasi_hapus;
    private javax.swing.JPanel tabelOperator2;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_ruang;
    private javax.swing.JTextField txt_nama_ruang;
    // End of variables declaration//GEN-END:variables
}
